language: go
go:
- 1.11
- 1.12

os:
  - linux
  - windows

env:
  global:
    - GO111MODULE=on

matrix:
  include:
  - go: 1.11
    env: GO111MODULE=off
  - go: 1.12
    env: GO111MODULE=on

install:
 - go get -u ./...
 - go mod download

after_install:
 - go mod tidy
 - go mod verify

script:
 - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
 - bash <(curl -s https://codecov.io/bash)
